source 'https://rubygems.org'

gem 'convert_it_core', path: '../../shared/convert_it_core', require: 'convert_it_rubymotion'
gem 'in_memory_repo', path: '../../shared/in_memory_repo', require: 'in_memory_repo_rubymotion'
